version: '3.5'

services:
  ### Jesse's Workspace ################################################
  jesse:
    image: salehmir/jesse:latest
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    command: >
      bash -c "
        until (echo > /dev/tcp/postgres/5432) >/dev/null 2>&1; do
          echo waiting for postgres;
          sleep 2;
        done;
        jesse install-live --no-strict && jesse run
      "
    tty: true
    env_file:
      - ../.env
    ports:
      - "9000:9000"
      # Jupyter Port
      - "8888:8888"
    volumes:
      - ../:/home
    container_name: jesse

  ### PostgreSQL ################################################
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=jesse_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=jesse_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    container_name: postgres
    healthcheck:
       test: ["CMD-SHELL", "pg_isready -U jesse_user"]
       interval: 5s
       timeout: 5s
       retries: 5

  ### Redis ################################################
  redis:
    image: redis:6-alpine
    container_name: redis
    command: redis-server --save "" --appendonly no
    
volumes:
  postgres-data:
